spring:
  liquibase:
    enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
security:
  jwt:
    secret: ZGhhc2xhc2Roc2FsZGhhc2Rhc2RrbGQvc2hhc2RoOz9BZGFzZDMyZWRzYw==
    access: 3600000
    refresh: 2592000000
