spring:
  liquibase:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/bivProjectBD
    username: postgres
    password: lens07gada
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
security:
  jwt:
    secret: ZGhhc2xhc2Roc2FsZGhhc2Rhc2RrbGQvc2hhc2RoOz9BZGFzZDMyZWRzYw==
    access: 3600000
    refresh: 2592000000
springdoc:
  override-with-generic-response: false